#! /bin/bash

if [ "$(whoami)" = "root" ]; then
    SUDO=""
else
    SUDO="sudo "
fi

if command -v apt > /dev/null; then
    PACKAGES=(
        git 
        ca-certificates 
        tmux 
        python3 
        command-not-found 
        bash-completion
        openssh-client
        less
        nano
    )

    ${SUDO} apt update
    ${SUDO} apt install "${PACKAGES[@]}"
else
    echo "I don't know your package manager."
    exit 1
fi
